# Generated by Django 2.0.1 on 2018-06-20 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(default=None, max_length=140, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testrun',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='tags',
            field=models.ManyToManyField(to='core.RunTag'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 17, 12, 19, 948062)),
        ),
    ]
