# Generated by Django 2.0.1 on 2018-06-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180620_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='executed',
        ),
        migrations.AlterField(
            model_name='testrun',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
