# Generated by Django 2.0.1 on 2018-08-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0003_auto_20180620_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TestTag',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='owner',
            new_name='author',
        ),

    ]
